server:
  port: 9000
logging:
  level:
    root: ERROR
    org.springframework.web: error
    org.hibernate: error
    cn.jinelei.rainbow.blog: debug
spring:
  profiles:
    active: dev
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: jinelei
    password: jinjinjin
upload:
  file:
    image: /file/image



---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://jinelei.cn:3306/blog?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: jinelei
    password: jin





---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: jinelei
    password: jinjinjin
